name: pocketvms
version: "0.6"
summary: A convergent QEMU frontend for desktop and mobile
description: |
  Pocket VMs is a QEMU frontend for Ubuntu Touch & Ubuntu Desktop

  Features:
  - A custom build of QEMU
  - A native & convergent GUI
  - Emulation (x86_64 on aarch64)
  - Virtualization (aarch64 on aarch64) using KVM
  - File sharing support
  - Easy to use machine management

grade: stable
confinement: strict
base: core20

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64

plugs:
  graphics-core20:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core20

layout:
  /usr/share/libdrm:  # Needed by mesa-core20 on AMD GPUs
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:  # Used by mesa-core20 for app specific workarounds
    bind: $SNAP/graphics/drirc.d
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts

apps:
  pocketvms:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/ceph:${SNAP}/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio:${SNAP}/usr/lib:${SNAP}/graphics/lib
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins
      QML2_IMPORT_PATH: ${SNAP}/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/qml
      XDG_DATA_DIRS: $XDG_DATA_DIRS:${SNAP}/usr/share
      PATH: ${SNAP}/bin:$PATH
    command: bin/desktop-launch /snap/pocketvms/current/bin/runner
    plugs:
      - audio-playback
      - audio-record
      - kvm
      - userns
      - home
      - opengl
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - network
      - network-bind
      - network-control
      - unity7
      - x11
      - wayland

parts:
  qtsystems:
    plugin: qmake
    qmake-project-file: qtsystems.pro
    source: https://github.com/qt/qtsystems.git
    source-commit: e3332ee38d27a134cef6621fdaf36687af1b6f4a
    override-build: |
      snapcraftctl build
      cp -a $SNAPCRAFT_PART_INSTALL/* /
    build-packages:
        - dbus
        - dbus-test-runner
        - devscripts
        - gdb
        - libdbus-1-dev
        - liblttng-ust-dev
        - libqt5svg5-dev
        - qtdeclarative5-dev
        - qtdeclarative5-private-dev
        - qtbase5-private-dev
  qtfeedback:
    plugin: qmake
    after: [ qtsystems ]
    qmake-project-file: qtfeedback.pro
    source: https://github.com/qt/qtfeedback.git
    source-commit: a14bd0bb1373cde86e09e3619fb9dc70f34c71f2
    override-build: |
      snapcraftctl build
      cp -a $SNAPCRAFT_PART_INSTALL/* /
    build-packages:
        - dbus
        - dbus-test-runner
        - devscripts
        - gdb
        - libdbus-1-dev
        - liblttng-ust-dev
        - libqt5svg5-dev
        - qtdeclarative5-dev
        - qtdeclarative5-private-dev
        - qtbase5-private-dev
  qtpim:
    after: [ qtfeedback ]
    plugin: qmake
    qmake-project-file: qtpim.pro
    source: https://github.com/qt/qtpim.git
    source-commit: 8fec622c186d254bc9750606d54c32670a9046a5
    override-build: |
      snapcraftctl build
      cp -a $SNAPCRAFT_PART_INSTALL/* /
    build-packages:
        - dbus
        - dbus-test-runner
        - devscripts
        - gdb
        - libdbus-1-dev
        - liblttng-ust-dev
        - libqt5svg5-dev
        - qtdeclarative5-dev
        - qtdeclarative5-private-dev
        - qtbase5-private-dev
  suru-icons:
    after: [ qtpim ]
    plugin: nil
    source: https://gitlab.com/ubports/core/suru-icon-theme.git
    source-branch: main
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons
      cp -a $SNAPCRAFT_PART_SRC/suru $SNAPCRAFT_PART_INSTALL/usr/share/icons/
  lomiri-ui-toolkit:
    plugin: qmake
    after: [ suru-icons ]
    qmake-project-file: lomiri-sdk.pro
    qmake-parameters:
        - CONFIG+=ubuntu-uitk-compat
    source: https://gitlab.com/ubports/core/lomiri-ui-toolkit.git
    source-branch: main
    override-build: |
      snapcraftctl build
      cp -a $SNAPCRAFT_PART_INSTALL/* /
    build-packages:
        - dbus
        - dbus-test-runner
        - devscripts
        - gdb
        - libdbus-1-dev
        - liblttng-ust-dev
        - libqt5svg5-dev
        - qtdeclarative5-dev
        - qtdeclarative5-private-dev
        - qtbase5-private-dev
        - qml-module-qtquick2
        - qml-module-qtquick-controls2
        - qml-module-qtquick-window2
        - qml-module-qtquick-layouts
        - qml-module-qtgraphicaleffects
        - qml-module-qttest
    stage-packages:
        - ttf-ubuntu-font-family
        - yaru-theme-icon
        - qml-module-qtquick2
        - qml-module-qtquick-window2
        - qml-module-qtquick-layouts
        - qml-module-qtgraphicaleffects
        - qml-module-qttest
        - libbluetooth3
        - liblttng-ust0
        - libnuma1
        - liburcu6
  pvms:
    source: .
    plugin: cmake
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      ./build.sh -c -l
    after: [ lomiri-ui-toolkit ]
    build-packages:
      - autoconf
      - automake
      - bison
      - flex
      - gettext
      - gtk-doc-tools
      - libtool
      - libaio-dev
      - libbluetooth-dev
      - libbrlapi-dev
      - libbz2-dev
      - libcap-dev
      - libcap-ng-dev
      - libcurl4-gnutls-dev
      - libdrm-dev
      - libgbm-dev
      - libgtk-3-dev
      - libibverbs-dev
      - libjemalloc-dev
      - libjpeg8-dev
      - libncurses5-dev
      - libnuma-dev
      - librbd-dev
      - librdmacm-dev
      - libsasl2-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libseccomp-dev
      - libsnappy-dev
      - libspice-protocol-dev
      - libspice-server-dev
      - libusb-1.0-0-dev
      - libusbredirparser-dev
      - libvde-dev
      - libvdeplug-dev
      - libvte-2.91-dev
      - libxen-dev
      - liblzo2-dev
      - libx11-dev
      - libxml2-dev
      - libepoxy-dev
      - libglib2.0-dev
      - libfdt-dev
      - libpixman-1-dev
      - xfslibs-dev
      - zlib1g-dev
      - libnfs-dev
      - libiscsi-dev
      - libpulse-dev
      - ninja-build
      - qml-module-qtquick2
      - qt5-qmake
      - qttools5-dev
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - qttools5-dev-tools
      - libqt5xmlpatterns5-dev
      - libqt5webkit5-dev
      - qtbase5-dev
      - qtquickcontrols2-5-dev
      - intltool
      - libvncserver-dev
      - libssl-dev
      - xutils-dev
      - meson
      - libva-dev
      - libslirp-dev
      - ovmf
    stage-packages:
      - libaio1
      - libbluetooth3
      - libboost-iostreams1.67.0
      - libboost-random1.67.0
      - libboost-thread1.67.0
      - libbrlapi0.7
      - libflac8
      - libiscsi7
      - libjemalloc2
      - libnfs13
      - libnuma1
      - librados2
      - librbd1
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsnappy1v5
      - libsndio7.0
      - libspice-server1
      - libusb-1.0-0
      - libusbredirparser1
      - libvdeplug2
      - libxencall1
      - libxendevicemodel1
      - libxenevtchn1
      - libxenforeignmemory1
      - libxengnttab1
      - libxenmisc4.11
      - libxenstore3.0
      - libxentoolcore1
      - libxentoollog1
      - libyajl2
      - libxi6
      - libxss1
      - libasn1-8-heimdal
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libbrotli1
      - libcairo-gobject2
      - libcairo2
      - libcurl3-gnutls
      - libdatrie1
      - libdrm2
      - libepoxy0
      - libfdt1
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgbm1
      - libgdk-pixbuf2.0-0
      - libgraphite2-3
      - libgssapi3-heimdal
      - libgtk-3-0
      - libharfbuzz0b
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libicu66
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libroken18-heimdal
      - librtmp1
      - libssh-4
      - libthai0
      - libvte-2.91-0
      - libvncclient1
      - libwayland-server0
      - libwind0-heimdal
      - libxcb-render0
      - libxcb-shm0
      - libxcomposite1
      - libxdamage1
      - qml-module-qtquick2
      - qml-module-qtquick-window2
      - qml-module-qtquick-dialogs
      - libdouble-conversion3
      - libevdev2
      - libpcre2-16-0
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5network5
      - libqt5qml5
      - libqt5quick5
      - libqt5sql5
      - libqt5svg5
      - libslirp0
      - libva-drm2
      - libva2
    prime:
      # Remove cruft
      - -usr/share/qemu/qemu-nsis.bmp
  runner:
    after: [ pvms ]
    source: snap/local
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av runner $SNAPCRAFT_PART_INSTALL/bin/
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - qtwayland5
      - fontconfig
      - fontconfig-config
      - locales-all
      - xdg-user-dirs
  qt-setup:
    after: [ runner ]
    source: https://github.com/snapcore/snapcraft-desktop-integration.git
    plugin: nil
    override-build: |
      cd qt-framework
      make PLATFORM_PLUG=desktop DESTDIR=$SNAPCRAFT_PART_INSTALL install
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - qtwayland5
      - fontconfig
      - fontconfig-config
      - locales-all
      - xdg-user-dirs
  cleanup:
    after: [ qt-setup ]
    plugin: nil
    build-snaps: [ mesa-core20 ]
    override-prime: |
      set -eux
      cd /snap/mesa-core20/current/egl/lib
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/{} \;
      rm -fr "$SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri"
      for CRUFT in bug drirc.d glvnd libdrm lintian man; do
        rm -rf "$SNAPCRAFT_PRIME/usr/share/$CRUFT"
      done
